[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
#requires = ["setuptools == 68.2.2"]

[project]
name = "ros_climatology_paper"
version = "1.0.0"
authors = [
  { name = "Andy Barrett", email = "andypbarrett@gmail.com" },
]
description = "A package containing scripts for rain-on-snow climatology paper"
readme = "README.md"
license.file = "LICENSE"

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]
test = [
  "pytest >=6",
]
dev = [
  "pytest >=6",
]